### ISSUE TITLE
Use same version in package.js and dockerode

### ISSUE THREAD

**Issue by mcbain** [ongoworks/meteor-dockerode#2]
It's easier to know which version is included when package uses same as dockerode.

**Comment by aaronjudd** [comment]
Really I think this package should be 1.0.4 -> that would the meteor / semver for this package..   It's tough to keep the meteor package the same version if you release 2.0.6 and then realized something was wrong -> you'd technically need to release 2.0.7 and then it'd be even more confusing.

**Comment by mcbain** [comment]
You can use 2.0.6-1 in such cases. see https://meteorhacks.com/meteor-packaging-system-understanding-versioning.html
